services:
  # suwayomi:
  #   image: ghcr.io/suwayomi/suwayomi-server:latest
  #   ports:
  #     - "4567:4567"
  #   volumes:
  #     - ../suwayomi:/home/suwayomi/.local/share/Tachidesk
  #   restart: unless-stopped

  backend:
    build: ../backend
    user: "${UID:-1000}:${GID:-1000}" # make sure the group has write permissions to the mounted volumes
    environment:
      ENV_FILE: "/app/data/.env"
      DATABASE_URL: "sqlite+aiosqlite:////app/data/otaki.db"
      LIBRARY_PATH: "/app/library"
      SUWAYOMI_DOWNLOAD_PATH: "/app/suwayomi_data"
      COVERS_PATH: "/app/covers"
      WATERMARKS_PATH: "/app/watermarks"
    volumes:
      - ../data:/app/data
      - ../suwayomi:/app/suwayomi_data
      - ../library:/app/library
      - ../covers:/app/covers
      - ../watermarks:/app/watermarks
    ports:
      - "8000:8000"
    restart: unless-stopped

  frontend:
    build: ../frontend
    ports:
      - "80:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - backend
    restart: unless-stopped
