"""add source_chapter_name and source_manga_title to chapter_assignments

Revision ID: 5ffa82538c2f
Revises: 9b822e5ef4dc
Create Date: 2026-03-29 22:15:53.039546

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ffa82538c2f'
down_revision: Union[str, Sequence[str], None] = '9b822e5ef4dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_assignments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_chapter_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('source_manga_title', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chapter_assignments', schema=None) as batch_op:
        batch_op.drop_column('source_manga_title')
        batch_op.drop_column('source_chapter_name')

    # ### end Alembic commands ###
