"""add_comic_source_overrides

Revision ID: a8e28f285f2e
Revises: d4e5f6a7b8c9
Create Date: 2026-04-09 09:53:43.481935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8e28f285f2e'
down_revision: Union[str, Sequence[str], None] = 'd4e5f6a7b8c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic_source_overrides',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('priority_override', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['comic_id'], ['comics.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('comic_id', 'source_id', name='uq_comic_source_overrides')
    )
    with op.batch_alter_table('comic_source_overrides', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comic_source_overrides_comic_id'), ['comic_id'], unique=False)

    with op.batch_alter_table('comic_aliases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comic_aliases_comic_id'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comic_aliases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comic_aliases_comic_id'), ['comic_id'], unique=False)

    with op.batch_alter_table('comic_source_overrides', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comic_source_overrides_comic_id'))

    op.drop_table('comic_source_overrides')
    # ### end Alembic commands ###
